# Generated by Django 5.2.17 on 2026-09-27 20:39

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("kind", models.CharField(max_length=30)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("external_adapter", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "secrets_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="extras.secretsgroup",
                    ),
                ),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("root", models.CharField(blank=True, max_length=500)),
                ("inventory", models.CharField(max_length=500)),
                ("map_spec", models.CharField(blank=True, max_length=500)),
                ("allow_delete", models.BooleanField(default=False)),
                ("no_adopt", models.BooleanField(default=False)),
                ("state_key", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "git_repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="extras.gitrepository",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_flows",
                        to="nautobot_alembic.backend",
                    ),
                ),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(
                        through="extras.TaggedItem", to="extras.Tag"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flows",
                        to="nautobot_alembic.backend",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("kind", models.CharField(default="plan", max_length=10)),
                ("status", models.CharField(default="pending", max_length=30)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("planned_at", models.DateTimeField(blank=True, null=True)),
                ("apply_started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("input", models.JSONField(blank=True, default=dict, editable=False)),
                ("input_entry", models.CharField(blank=True, editable=False, max_length=500)),
                ("input_sha256", models.CharField(blank=True, max_length=64)),
                ("plan", models.TextField(blank=True, editable=False)),
                ("plan_sha256", models.CharField(blank=True, max_length=64)),
                ("approved_sha256", models.CharField(blank=True, max_length=64)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("drift_report", models.JSONField(blank=True, null=True)),
                ("apply_report", models.JSONField(blank=True, null=True)),
                ("alembic_version", models.CharField(blank=True, max_length=30)),
                ("error", models.TextField(blank=True)),
                ("output", models.TextField(blank=True, editable=False)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="nautobot_alembic.flow",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "permissions": [("approve_run", "Approve or reject a run")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "applying",
                                    "approved",
                                    "awaiting_approval",
                                    "pending",
                                    "planning",
                                ],
                            )
                        ),
                        fields=("flow",),
                        name="nautobot_alembic_run_one_active_per_flow",
                        violation_error_message="This flow already has a run in progress.",
                    )
                ],
            },
        ),
    ]
