# Generated by Django 6.0.5 on 2026-09-27 11:23

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_job_notifications'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credential', models.CharField(blank=True, max_length=100)),
                ('external_adapter', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'backend',
                'verbose_name_plural': 'backends',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('root', models.CharField(blank=True, max_length=500)),
                ('inventory', models.CharField(max_length=500)),
                ('allow_delete', models.BooleanField(default=False)),
                ('no_adopt', models.BooleanField(default=False)),
                ('state_key', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.datasource')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='netbox_alembic.backend')),
            ],
            options={
                'verbose_name': 'flow',
                'verbose_name_plural': 'flows',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.CharField(default='plan', max_length=10)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('apply_started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, default=dict, editable=False)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('plan', models.TextField(blank=True, editable=False)),
                ('plan_sha256', models.CharField(blank=True, max_length=64)),
                ('approved_sha256', models.CharField(blank=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('drift_report', models.JSONField(blank=True, null=True)),
                ('apply_report', models.JSONField(blank=True, null=True)),
                ('alembic_version', models.CharField(blank=True, max_length=30)),
                ('error', models.TextField(blank=True)),
                ('output', models.TextField(blank=True, editable=False)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='netbox_alembic.flow')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'run',
                'verbose_name_plural': 'runs',
                'ordering': ('-created',),
                'permissions': [('approve_run', 'approve or reject a run')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['applying', 'approved', 'awaiting_approval', 'pending', 'planning'])), fields=('flow',), name='netbox_alembic_run_one_active_per_flow', violation_error_message='This flow already has a run in progress.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
