# Generated by Django 6.0.5 on 2026-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_alembic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backend",
            name="external_adapter",
        ),
        migrations.AlterField(
            model_name="backend",
            name="kind",
            field=models.CharField(max_length=100),
        ),
    ]
